### ISSUE TITLE
this project has some problem

### ISSUE THREAD

**Issue by vinayakbhovi** [arkprocoder/Farm-management-sysem-dbmsminiproject#1]
i am getting the following problem after executing the main.py file

PS C:\Users\vinay\Desktop\farmer system> & C:/Users/vinay/AppData/Local/Programs/Python/Python310/python.exe "c:/Users/vinay/Desktop/farmer system/main.py"
Traceback (most recent call last):
  File "c:\Users\vinay\Desktop\farmer system\main.py", line 3, in <module>
    from flask_login import UserMixin
  File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_login\__init__.py", line 16, in <module>
    from .login_manager import LoginManager
  File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_login\login_manager.py", line 24, in <module>
    from .utils import (login_url as make_login_url, _create_identifier,
  File "C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_login\utils.py", line 13, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (C:\Users\vinay\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\security.py)

please help......

![Uploading image_2022-03-28_232310.png…]()

**Comment by dayacode12** [comment]
IT IS WORKING BRO

**Comment by Sahan12fhtvidjofvifjigkfj** [comment]
I am getting jinja2.exceptions.templatenotfound index.html 
Why is it showing so please help to resolve this issue

**Comment by Varshanthg** [comment]
@vinayakbhovi u have not installed usermixin ,LoginManager ,safe_str_cmp i think you just have default flask library
install using following command
pip install Flask-Login
etc etc

**Comment by Varshanthg** [comment]
@Sahan12fhtvidjofvifjigkfj when u dont  have the frontend code i.e index.html and css files your backend flask code will not be able to fetch it and hence u get jinja2.exceptions.templatenotfound index.html so download "templates" and "static" folders and try it
